include: "rules/common.smk"


##### Target rules #####


rule all:
    input:
        expand(f"{OUTPUT_DIR}/4.bismark_methylation/{{sample}}", sample=SAMPLES)


##### Modules #####


include: "rules/filter.smk"
include: "rules/align.smk"
include: "rules/dedulplicate.smk"
include: "rules/callmethy.smk"
