outdir: /home/liuxin/data_pasteur/12_epigenome/1.Samples
ref: /home/liuxin/data_pasteur/12_epigenome/CHM13_ref
sample: /home/liuxin/data_pasteur/12_epigenome/sample_10.txt
threads:
  bis_align: 8
  bis_call: 12
  bis_dedul: 12
  soapnuke: 24
