outdir: /home/liuxin/data_pasteur/12_epigenome/1.Samples
ref: /home/liuxin/data_pasteur/12_epigenome/CHM13_ref
sample: /home/liuxin/data_pasteur/12_epigenome/sample.txt
threads:
  bis_align: 6
  bis_call: 8
  bis_dedul: 8
  soapnuke: 14
